data:
    communication:
        id: P2YAQ80HI1TYGXJISCUD
        listenport: "9001"
        targets:
            - localhost:80
    routing:
        routes:
            - route-a
        terminator: false
    settings:
        interval: 3s
