data:
    communication:
        id: "ENDPOINT-ALPHA"
        listenport: "9001"
        targets:
            - 0.0.0.0:9002
            - 0.0.0.0:9003
    routing:
        routes:
            - route-a
            - route-b
        terminator: true
    settings:
        interval: 500ms
