// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0
// source: protoraw/status.proto

package pt3status

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lst []*Status_Chain `protobuf:"bytes,1,rep,name=lst,proto3" json:"lst,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoraw_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_protoraw_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_protoraw_status_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetLst() []*Status_Chain {
	if x != nil {
		return x.Lst
	}
	return nil
}

type Echo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Echo string `protobuf:"bytes,1,opt,name=echo,proto3" json:"echo,omitempty"`
}

func (x *Echo) Reset() {
	*x = Echo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoraw_status_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo) ProtoMessage() {}

func (x *Echo) ProtoReflect() protoreflect.Message {
	mi := &file_protoraw_status_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo.ProtoReflect.Descriptor instead.
func (*Echo) Descriptor() ([]byte, []int) {
	return file_protoraw_status_proto_rawDescGZIP(), []int{1}
}

func (x *Echo) GetEcho() string {
	if x != nil {
		return x.Echo
	}
	return ""
}

type Status_Chain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Terminator  bool     `protobuf:"varint,2,opt,name=terminator,proto3" json:"terminator,omitempty"`
	LastUpdated string   `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Health      int32    `protobuf:"varint,4,opt,name=health,proto3" json:"health,omitempty"`
	Targets     int32    `protobuf:"varint,5,opt,name=targets,proto3" json:"targets,omitempty"`
	Routes      []string `protobuf:"bytes,6,rep,name=routes,proto3" json:"routes,omitempty"`
}

func (x *Status_Chain) Reset() {
	*x = Status_Chain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoraw_status_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status_Chain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status_Chain) ProtoMessage() {}

func (x *Status_Chain) ProtoReflect() protoreflect.Message {
	mi := &file_protoraw_status_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status_Chain.ProtoReflect.Descriptor instead.
func (*Status_Chain) Descriptor() ([]byte, []int) {
	return file_protoraw_status_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Status_Chain) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Status_Chain) GetTerminator() bool {
	if x != nil {
		return x.Terminator
	}
	return false
}

func (x *Status_Chain) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *Status_Chain) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *Status_Chain) GetTargets() int32 {
	if x != nil {
		return x.Targets
	}
	return 0
}

func (x *Status_Chain) GetRoutes() []string {
	if x != nil {
		return x.Routes
	}
	return nil
}

var File_protoraw_status_proto protoreflect.FileDescriptor

var file_protoraw_status_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x72, 0x61, 0x77, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x74, 0x33, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0xda, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x29, 0x0a,
	0x03, 0x6c, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x74, 0x33,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x43, 0x68,
	0x61, 0x69, 0x6e, 0x52, 0x03, 0x6c, 0x73, 0x74, 0x1a, 0xa4, 0x01, 0x0a, 0x05, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74,
	0x6f, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x18, 0x0a,
	0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x22,
	0x1a, 0x0a, 0x04, 0x45, 0x63, 0x68, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x63, 0x68, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65, 0x63, 0x68, 0x6f, 0x32, 0x3b, 0x0a, 0x0b, 0x45,
	0x63, 0x68, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x50, 0x6f,
	0x6b, 0x65, 0x12, 0x0f, 0x2e, 0x70, 0x74, 0x33, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x45,
	0x63, 0x68, 0x6f, 0x1a, 0x11, 0x2e, 0x70, 0x74, 0x33, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x70, 0x74,
	0x33, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoraw_status_proto_rawDescOnce sync.Once
	file_protoraw_status_proto_rawDescData = file_protoraw_status_proto_rawDesc
)

func file_protoraw_status_proto_rawDescGZIP() []byte {
	file_protoraw_status_proto_rawDescOnce.Do(func() {
		file_protoraw_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoraw_status_proto_rawDescData)
	})
	return file_protoraw_status_proto_rawDescData
}

var file_protoraw_status_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protoraw_status_proto_goTypes = []interface{}{
	(*Status)(nil),       // 0: pt3status.Status
	(*Echo)(nil),         // 1: pt3status.Echo
	(*Status_Chain)(nil), // 2: pt3status.Status.Chain
}
var file_protoraw_status_proto_depIdxs = []int32{
	2, // 0: pt3status.Status.lst:type_name -> pt3status.Status.Chain
	1, // 1: pt3status.EchoService.Poke:input_type -> pt3status.Echo
	0, // 2: pt3status.EchoService.Poke:output_type -> pt3status.Status
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protoraw_status_proto_init() }
func file_protoraw_status_proto_init() {
	if File_protoraw_status_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoraw_status_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoraw_status_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Echo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoraw_status_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status_Chain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoraw_status_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoraw_status_proto_goTypes,
		DependencyIndexes: file_protoraw_status_proto_depIdxs,
		MessageInfos:      file_protoraw_status_proto_msgTypes,
	}.Build()
	File_protoraw_status_proto = out.File
	file_protoraw_status_proto_rawDesc = nil
	file_protoraw_status_proto_goTypes = nil
	file_protoraw_status_proto_depIdxs = nil
}
